<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Deploy.Enterprise.Tests</RootNamespace>
    <AssemblyName>Deploy.Enterprise.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\community\src\Modules\Deploy\ForgeDeck.Deploy\ForgeDeck.Deploy.csproj" />
    <ProjectReference Include="..\..\..\community\src\Core\ForgeDeck.Core\ForgeDeck.Core.csproj" />
    <ProjectReference Include="..\..\team\Modules\Deploy.Team\ForgeDeck.Deploy.Team\ForgeDeck.Deploy.Team.csproj" />
    <ProjectReference Include="..\..\enterprise\Modules\Deploy.Enterprise\ForgeDeck.Deploy.Enterprise\ForgeDeck.Deploy.Enterprise.csproj" />
    <ProjectReference Include="..\..\..\sdk\ForgeDeck.Contracts\ForgeDeck.Contracts.csproj" />
  </ItemGroup>

</Project>
